train_dataset <- read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/train/X_train.txt")
test_dataset <- read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/test/X_test.txt")
train_labels<-read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/train/Y_train.txt")
test_labels<-read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/test/Y_test.txt")
subject_train<-read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/train/subject_train.txt")
subject_test<-read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/test/subject_test.txt")
train_data <- cbind(cbind(subject_train,train_dataset),train_labels)
features <- read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/features.txt",colClasses = c("character"))
test_data<-cbind(cbind(subject_test,test_dataset),test_labels)
final_data<-rbind(train_data,test_data)
activities<-read.table("C:/Users/Sai Vamshi/Desktop/R files/UCI HAR Dataset/activity_labels.txt",col.names = c("Id","Activity"))
names(final_data)<-rbind(rbind(c(1, "Subject"),features), c(563, "Id"))[,2]
measurements<-grepl("mean|std|Subject|Id",names(final_data))
meanstd<-final_data[measurements]
meanstd<-merge(meanstd,activities,by.x = "Id")
meanstd<-meanstd[,-1]
meanstd<-meanstd[,c(1,81,2:80)]
library(dplyr)
meanstd<-arrange(meanstd,Subject)
n1<-names(meanstd)
names(meanstd) <- gsub('\\(|\\)',"",n1, perl = TRUE)
names(meanstd) <- make.names(n1)
names(meanstd)<- gsub('Acc',"Acceleration",n1)
names(meanstd)<- gsub('GyroJerk',"AngularAcceleration",n1)
names(meanstd)<- gsub('Gyro',"AngularSpeed",n1)
names(meanstd)<- gsub('Mag',"Magnitude",n1)
names(meanstd)<- gsub('\\.mean',".Mean",n1)
names(meanstd)<- gsub('\\.std',".StandardDeviation",n1)
names(meanstd)<- gsub('Freq\\.',"Frequency.",n1)
names(meanstd)<- gsub('^t',"TimeDomain.",n1)
names(meanstd) <- gsub('^f',"FrequencyDomain.",n1)
library(plyr)
avg= ddply(meanstd, c("Subject","Activity"), numcolwise(mean))
write.table(avg, file = "average.txt")h)